### PR TITLE
feat(Migrated from TSLint to ESLint)

### PR DESCRIPTION
**Pull request by taha437**
## Description

I made the necessary changes to package.json to support ESLint in favour of TSLint i.e. added dependencies and necessary scripts. A new .eslintrc.json file was created that contains all the rules for ESLint. tslint.js file was removed because it is no longer required.

## Motivation and Context

This change was necessary because support for TSLint is going to be deprecated in favour of ESLint. So the sooner we make the switch the better.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by artalat** [comment]
This migrates 100% rules?

**Comment by taha437** [comment]
> This migrates 100% rules?

I added all the rules written in tslint.js file. Not sure if those were all of them.

**Comment by artalat** [comment]
Did you use a migration tool or did it all manually?

**Comment by taha437** [comment]
> Did you use a migration tool or did it all manually?

Manually.

**Comment by artalat** [comment]
can you look at these and see if the output is any different:

https://github.com/typescript-eslint/tslint-to-eslint-config
https://dev.to/cosmvs/tslint-eslint-cra-typescript-prettier-2h40

**Comment by taha437** [comment]
I implemented the approach mentioned in this document: 
[https://github.com/typescript-eslint/tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config). 
The output is different in the sense that this package does not remove tslint packages in package.json those i think we have to manually remove. Other than that it generates this log file of jsx rules and some others that do not have an ESLint equivalent (attached below). I think we have to add these manually as well. Rest is the same for both manual approach and using this migration tool. 
[tslint-to-eslint-config.log](https://github.com/BlueBaseJS/code-standards/files/3615615/tslint-to-eslint-config.log)

**Comment by artalat** [comment]
@ammarkhan967 when can we close this?

**Comment by taha437** [comment]
@artalat kindly review and merge this

**Review by artalat — APPROVED** [review]

**Pull request merged**
